services:
  server:
    build:
      context: ../..
      dockerfile: packages/twenty-docker/twenty/Dockerfile
      target: twenty
    image: strongesthd/crm:local
    ports: !override
      - "127.0.0.1:3002:3000"

  worker:
    image: strongesthd/crm:local
